export { default as Error } from './Error'
export { default as Header } from './Header'
export { default as Loader } from './Loader'
export { default as Main } from './Main'
export { default as Question } from './Question'
export { default as StartScreen } from './StartScreen'
